# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

# global configuration
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10


# release filters
releaseFilters: &releaseFilters
  filters:
      tags: 
        only: /^v.*/
      branches:
        ignore: /.*/

# default filters
defaultFilters: &defaultFilters
  filters:
    tags:
      ignore:
        -/.*/
      branches:
        only:
          - /feature\/.*/
          - master

restoreCacheConfig: &restoreCacheConfig
  keys:
    - v1-dependencies-{{ checksum "package.json" }}
    # fallback to usng latest cache just in case ..
    - v1-dependencies-

saveCacheConfig: &saveCacheConfig
  paths:
    - node_modules
  key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
        <<: *restoreCacheConfig

      - run: npm install
      - run:
          name: Run tests
          command: npm run test-publish-coverage

      - save_cache:
        <<: *saveCacheConfig

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          <<: *releaseFilters
          requires:
            - test
